const AnimalProtein = {
    "egg": "Animal Protein",
    "chicken": "Animal Protein",
    "beef": "Animal Protein",
    "crab": "Animal Protein",
    "tuna": "Animal Protein",
  "sardines": "Animal Protein",
  "shrimp": "Animal Protein",
  "duck": "Animal Protein",
  "pork": "Animal Protein",
  "goat cheese": "Animal Protein",
  "beef": "Animal Protein",
  "chicken": "Animal Protein",
  "lamb": "Animal Protein",
  "turkey": "Animal Protein",
  "fish": "Animal Protein",
  "eggs": "Animal Protein",
  "milk": "Animal Protein",
  "cheese": "Animal Protein",
  "yogurt": "Animal Protein",
  "butter": "Animal Protein",
  "beef jerky": "Animal Protein",
  "chicken nuggets": "Animal Protein",
  "fish sticks": "Animal Protein",
  "bacon": "Animal Protein",
  "sausage": "Animal Protein",
  "ham": "Animal Protein",
  "hot dogs": "Animal Protein",
  "beef jerky": "Animal Protein",
  "chicken nuggets": "Animal Protein",
  "fish sticks": "Animal Protein",
  "bacon": "Animal Protein",
  "sausage": "Animal Protein",
  "ham": "Animal Protein",
  "hot dogs": "Animal Protein",
  "beef jerky": "Animal Protein",
  "chicken nuggets": "Animal Protein",
  "fish sticks": "Animal Protein",
  "bacon": "Animal Protein",
  "sausage": "Animal Protein",
  "ham": "Animal Protein",
  "hot dogs": "Animal Protein",
  "beef jerky": "Animal Protein",
  "chicken nuggets": "Animal Protein",
  "fish sticks": "Animal Protein",
  "bacon": "Animal Protein",
  "sausage": "Animal Protein",
  "ham": "Animal Protein",
  "hot dogs": "Animal Protein",
  "beef jerky": "Animal Protein",
  "chicken nuggets": "Animal Protein",
  "fish sticks": "Animal Protein",
  "bacon": "Animal Protein",
  "sausage": "Animal Protein",
  "ham": "Animal Protein",
  "hot dogs": "Animal Protein",
  "beef jerky": "Animal Protein",
  "chicken nuggets": "Animal Protein",
  "fish sticks": "Animal Protein",
  "bacon": "Animal Protein",
  "sausage": "Animal Protein",
  "ham": "Animal Protein",
  "hot dogs": "Animal Protein",
  "beef jerky": "Animal Protein",
  "chicken nuggets": "Animal Protein",
  "fish sticks": "Animal Protein",
  "bacon": "Animal Protein",
  "sausage": "Animal Protein",
  "ham": "Animal Protein",
  "hot dogs": "Animal Protein",
  "beef jerky": "Animal Protein",
  "chicken nuggets": "Animal Protein",
  "fish sticks": "Animal Protein",
  "bacon": "Animal Protein",
  "sausage": "Animal Protein",
  "ham": "Animal Protein",
  "hot dogs": "Animal Protein"
}
