const Fats = {
  "pumpkin seeds": "Fats",
  "sunflower seeds": "Fats",
  "sesame seeds": "Fats",
  "tahini": "Fats",
  "macadamia nuts": "Fats",
  "almonds": "Fats",
  "cashews": "Fats",
  "pecans": "Fats",
  "pistachios": "Fats",
  "walnuts": "Fats",
  "hazelnuts": "Fats",
  "pine nuts": "Fats",
  "peanuts": "Fats",
  "avocado": "Fats",
  "olive oil": "Fats",
  "coconut oil": "Fats",
  "butter": "Fats",
  "ghee": "Fats",
  "lard": "Fats",
  "tallow": "Fats",
  "beef fat": "Fats",
  "chicken fat": "Fats",
  "duck fat": "Fats",
  "goose fat": "Fats",
  "fish oil": "Fats",
  "cod liver oil": "Fats",
  "flaxseed oil": "Fats",
  "hemp seed oil": "Fats",
  "chia seed oil": "Fats",
  "evening primrose oil": "Fats",
  "borage oil": "Fats",
  "black cumin seed oil": "Fats",
  "starflower oil": "Fats",
  "butterbur oil": "Fats",
  "mayonnaise": "Fats",
  "aioli": "Fats",
  "ranch dressing": "Fats",
  "Caesar dressing": "Fats",
  "blue cheese dressing": "Fats",
  "thousand island dressing": "Fats",
  "vinaigrette": "Fats",
  "pesto": "Fats",
  "hummus": "Fats",
  "guacamole": "Fats",
  "salsa": "Fats",
  "sauerkraut": "Fats",
  "kimchi": "Fats",
  "pickles": "Fats",
  "olives": "Fats",
  "capers": "Fats",
  "sun-dried tomatoes": "Fats",
  "bacon": "Fats",
  "sausage": "Fats",
  "ham": "Fats",
  "hot dogs": "Fats",
  "beef jerky": "Fats",
  "chicken nuggets": "Fats",
  "fish sticks": "Fats",
  "french fries": "Fats",
  "potato chips": "Fats",
  "tortilla chips": "Fats",
  "popcorn": "Fats",
  "dark chocolate": "Fats",
  "milk chocolate": "Fats",
  "white chocolate": "Fats",
  "ice cream": "Fats",
  "yogurt": "Fats",
  "cheese": "Fats",
  "margarine": "Fats",
  "shortening": "Fats",
  "dripping": "Fats",
  "schmaltz": "Fats",
  "clarified butter": "Fats"
};
