const PlantProtein = {
    "tofu": "Plant Protein",
   "tempeh": "Plant Protein",
    "hummus": "Plant Protein",
    "seitan": "Plant Protein",
    "lentils": "Plant Protein",
  "tempeh": "Plant Protein",
  "hummus": "Plant Protein",
  "seitan": "Plant Protein",
  "tofu": "Plant Protein",
  "edamame": "Plant Protein",
  "lentils": "Plant Protein",
  "chickpeas": "Plant Protein",
  "black beans": "Plant Protein",
  "pinto beans": "Plant Protein",
  "kidney beans": "Plant Protein",
  "lima beans": "Plant Protein",
  "soybeans": "Plant Protein",
  "split peas": "Plant Protein",
  "nuts": "Plant Protein",
  "seeds": "Plant Protein",
  "quinoa": "Plant Protein",
  "buckwheat": "Plant Protein",
  "amaranth": "Plant Protein",
  "hemp seeds": "Plant Protein",
  "chia seeds": "Plant Protein",
  "spirulina": "Plant Protein",
  "algae": "Plant Protein",
  "wheat gluten": "Plant Protein",
  "rice protein": "Plant Protein",
  "pea protein": "Plant Protein",
  "hemp protein": "Plant Protein",
  "soy protein isolate": "Plant Protein",
  "vegetable protein powder": "Plant Protein"
}
