const Starches = {
    "barley": "Starches",
    "farro": "Starches",
    "millet": "Starches",
    "buckwheat": "Starches",
    "cassava": "Starches",
  "barley": "Starches",
  "farro": "Starches",
  "millet": "Starches",
  "buckwheat": "Starches",
  "cassava": "Starches",
  "rice": "Starches",
  "wheat": "Starches",
  "corn": "Starches",
  "potatoes": "Starches",
  "sweet potatoes": "Starches",
  "yams": "Starches",
  "plantains": "Starches",
  "tapioca": "Starches",
  "quinoa": "Starches",
  "amaranth": "Starches",
  "sorghum": "Starches",
  "teff": "Starches",
  "bread": "Starches",
  "pasta": "Starches",
  "cereal": "Starches",
  "crackers": "Starches",
  "cookies": "Starches",
  "cakes": "Starches",
  "pies": "Starches",
  "donuts": "Starches",
  "bagels": "Starches",
  "pancakes": "Starches",
  "waffles": "Starches",
  "muffins": "Starches",
  "scones": "Starches",
  "biscuits": "Starches",
  "tortillas": "Starches",
  "wraps": "Starches",
  "rice cakes": "Starches",
  "popcorn": "Starches",
  "pretzels": "Starches",
  "chips": "Starches",
  "noodles": "Starches",
  "couscous": "Starches",
  "bulgur wheat": "Starches",
  "oatmeal": "Starches",
  "rice pudding": "Starches",
  "bread pudding": "Starches",
  "potato salad": "Starches",
  "pasta salad": "Starches",
  "mac and cheese": "Starches",
  "pizza": "Starches",
  "burrito": "Starches",
  "taco": "Starches",
  "enchilada": "Starches",
  "quesadilla": "Starches",
  "nachos": "Starches",
  "sushi": "Starches",
  "ramen": "Starches",
  "pho": "Starches",
  "pad thai": "Starches",
  "curry": "Starches",
  "stew": "Starches",
  "soup": "Starches",
  "chili": "Starches",
  "sauce": "Starches",
  "gravy": "Starches",
  "syrup": "Starches",
  "honey": "Starches",
  "maple syrup": "Starches",
  "agave nectar": "Starches",
  "rice syrup": "Starches",
  "corn syrup": "Starches"
}
