const SweetFruits = {
  "lychee": "Sweet Fruits",
  "papaya": "Sweet Fruits",
  "guava": "Sweet Fruits",
  "mango": "Sweet Fruits",
  "pineapple": "Sweet Fruits",
  "banana": "Sweet Fruits",
  "grape": "Sweet Fruits",
  "plum": "Sweet Fruits",
  "peach": "Sweet Fruits",
  "pear": "Sweet Fruits",
  "apple": "Sweet Fruits",
  "cherry": "Sweet Fruits",
  "strawberry": "Sweet Fruits",
  "raspberry": "Sweet Fruits",
  "blueberry": "Sweet Fruits",
  "blackberry": "Sweet Fruits",
  "kiwi": "Sweet Fruits",
  "watermelon": "Sweet Fruits",
  "honeydew melon": "Sweet Fruits",
  "cantaloupe": "Sweet Fruits",
  "fig": "Sweet Fruits",
  "date": "Sweet Fruits",
  "coconut": "Sweet Fruits"
};
