const Vegetables = {
    "green beans": "Vegetables",
    "brussels sprouts": "Vegetables",
    "eggplant": "Vegetables",
    "mushrooms": "Vegetables",
    "cauliflower": "Vegetables",
    "artichoke": "Vegetables",
  "brussels sprouts": "Vegetables",
  "eggplant": "Vegetables",
  "mushrooms": "Vegetables",
  "cauliflower": "Vegetables",
  "artichoke": "Vegetables",
  "broccoli": "Vegetables",
  "carrots": "Vegetables",
  "potatoes": "Vegetables",
  "onions": "Vegetables",
  "garlic": "Vegetables",
  "ginger": "Vegetables",
  "tomatoes": "Vegetables",
  "cucumbers": "Vegetables",
  "zucchini": "Vegetables",
  "squash": "Vegetables",
  "pumpkin": "Vegetables",
  "bell peppers": "Vegetables",
  "jalapeno peppers": "Vegetables",
  "chili peppers": "Vegetables",
  "spinach": "Vegetables",
  "kale": "Vegetables",
  "collard greens": "Vegetables",
  "turnip greens": "Vegetables",
  "mustard greens": "Vegetables",
  "bok choy": "Vegetables",
  "napa cabbage": "Vegetables",
  "lettuce": "Vegetables",
  "celery": "Vegetables",
  "asparagus": "Vegetables",
  "peas": "Vegetables",
  "beans": "Vegetables",
  "corn": "Vegetables",
  "carrots": "Vegetables",
  "beets": "Vegetables",
  "parsnips": "Vegetables",
  "rutabaga": "Vegetables",
  "turnips": "Vegetables",
  "radishes": "Vegetables",
  "okra": "Vegetables",
  "eggplant": "Vegetables",
  "mushrooms": "Vegetables",
  "artichokes": "Vegetables",
  "broccoli rabe": "Vegetables",
  "kale": "Vegetables",
  "collard greens": "Vegetables",
  "mustard greens": "Vegetables",
  "turnip greens": "Vegetables",
  "bok choy": "Vegetables",
  "napa cabbage": "Vegetables",
  "lettuce": "Vegetables",
  "spinach": "Vegetables",
  "celery": "Vegetables",
  "asparagus": "Vegetables",
  "peas": "Vegetables",
  "green beans": "Vegetables",
  "lima beans": "Vegetables",
  "kidney beans": "Vegetables",
  "pinto beans": "Vegetables",
  "black beans": "Vegetables",
  "chickpeas": "Vegetables",
  "lentils": "Vegetables",
  "corn": "Vegetables",
  "carrots": "Vegetables",
  "beets": "Vegetables",
  "parsnips": "Vegetables",
  "rutabaga": "Vegetables",
  "turnips": "Vegetables",
  "radishes": "Vegetables",
  "okra": "Vegetables",
  "eggplant": "Vegetables",
  "mushrooms": "Vegetables",
  "artichokes": "Vegetables",
  "broccoli rabe": "Vegetables",
  "kale": "Vegetables",
  "collard greens": "Vegetables",
  "mustard greens": "Vegetables",
  "turnip greens": "Vegetables",
  "bok choy": "Vegetables",
  "napa cabbage": "Vegetables",
  "lettuce": "Vegetables",
  "spinach": "Vegetables",
  "celery": "Vegetables",
  "asparagus": "Vegetables",
  "peas": "Vegetables",
  "green beans": "Vegetables",
  "lima beans": "Vegetables",
  "kidney beans": "Vegetables",
  "pinto beans": "Vegetables",
  "black beans": "Vegetables",
  "chickpeas": "Vegetables",
  "lentils": "Vegetables",
  "corn": "Vegetables",
  "carrots": "Vegetables",
  "beets": "Vegetables",
  "parsnips": "Vegetables",
  "rutabaga": "Vegetables",
  "turnips": "Vegetables",
  "radishes": "Vegetables",
  "okra": "Vegetables",
  "eggplant": "Vegetables",
  "mushrooms": "Vegetables",
  "artichokes": "Vegetables",
  "broccoli rabe": "Vegetables",
  "kale": "Vegetables",
  "collard greens": "Vegetables",
  "mustard greens": "Vegetables",
  "turnip greens": "Vegetables",
  "bok choy": "Vegetables",
  "napa cabbage": "Vegetables",
  "lettuce": "Vegetables",
  "spinach": "Vegetables",
  "celery": "Vegetables",
  "asparagus": "Vegetables",
  "peas": "Vegetables",
  "green beans": "Vegetables",
  "lima beans": "Vegetables",
  "kidney beans": "Vegetables",
  "pinto beans": "Vegetables",
  "black beans": "Vegetables",
  "chickpeas": "Vegetables",
  "lentils": "Vegetables",
  "corn": "Vegetables",
  "carrots": "Vegetables",
  "beets": "Vegetables",
  "parsnips": "Vegetables",
  "rutabaga": "Vegetables",
  "turnips": "Vegetables",
  "radishes": "Vegetables",
  "okra": "Vegetables",
  "eggplant": "Vegetables",
  "mushrooms": "Vegetables",
  "artichokes": "Vegetables",
  "broccoli rabe": "Vegetables",
  "kale": "Vegetables",
  "collard greens": "Vegetables",
  "mustard greens": "Vegetables",
  "turnip greens": "Vegetables",
  "bok choy": "Vegetables",
  "napa cabbage": "Vegetables",
  "lettuce": "Vegetables",
  "spinach": "Vegetables",
  "celery": "Vegetables",
  "asparagus": "Vegetables",
  "peas": "Vegetables",
  "green beans": "Vegetables",
  "lima beans": "Vegetables",
  "kidney beans": "Vegetables",
  "pinto beans": "Vegetables",
  "black beans": "Vegetables",
  "chickpeas": "Vegetables",
  "lentils": "Vegetables",
  "corn": "Vegetables",
  "carrots": "Vegetables",
  "beets": "Vegetables",
  "parsnips": "Vegetables",
  "rutabaga": "Vegetables",
  "turnips": "Vegetables",
  "radishes": "Vegetables",
  "okra": "Vegetables",
  "eggplant": "Vegetables",
  "mushrooms": "Vegetables",
  "artichokes": "Vegetables",
  "broccoli rabe": "Vegetables",
  "kale": "Vegetables",
  "collard greens": "Vegetables",
  "mustard greens": "Vegetables",
  "turnip greens": "Vegetables",
  "bok choy": "Vegetables",
  "napa cabbage": "Vegetables",
  "lettuce": "Vegetables",
  "spinach": "Vegetables",
  "celery": "Vegetables",
  "asparagus": "Vegetables",
  "peas": "Vegetables",
  "green beans": "Vegetables",
  "lima beans": "Vegetables",
  "kidney beans": "Vegetables",
  "pinto beans": "Vegetables",
  "black beans": "Vegetables",
  "chickpeas": "Vegetables",
  "lentils": "Vegetables",
  "corn": "Vegetables",
  "carrots": "Vegetables",
  "beets": "Vegetables",
  "parsnips": "Vegetables",
  "rutabaga": "Vegetables",
  "turnips": "Vegetables",
  "radishes": "Vegetables",
  "okra": "Vegetables",
  "eggplant": "Vegetables",
  "mushrooms": "Vegetables",
  "artichokes": "Vegetables",
  "broccoli rabe": "Vegetables",
  "kale": "Vegetables",
  "collard greens": "Vegetables",
  "mustard greens": "Vegetables",
  "turnip greens": "Vegetables",
  "bok choy": "Vegetables",
  "napa cabbage": "Vegetables",
  "lettuce": "Vegetables",
  "spinach": "Vegetables",
  "celery": "Vegetables",
  "asparagus": "Vegetables",
  "peas": "Vegetables",
  "green beans": "Vegetables",
  "lima beans": "Vegetables",
  "kidney beans": "Vegetables",
  "pinto beans": "Vegetables",
  "black beans": "Vegetables",
  "chickpeas": "Vegetables",
  "lentils": "Vegetables",
  "corn": "Vegetables",
  "carrots": "Vegetables",
  "beets": "Vegetables",
  "parsnips": "Vegetables",
  "rutabaga": "Vegetables",
  "turnips": "Vegetables",
  "radishes": "Vegetables",
  "okra": "Vegetables",
  "eggplant": "Vegetables",
  "mushrooms": "Vegetables"
}
